### ISSUE TITLE
Readme note question

### ISSUE THREAD

**Issue by matthewchung74** [kopurando/better-faster-elastic-beanstalk#1]
Hello Kopurando, 

Can you add a note for how to use this project? Is it as simple as taking the example_env.config, tweaking the node version, and placing it in my .ebextensions?

**Comment by kopurando** [comment]
will do... this repo got more popular than I expected, thanks for the notice.

**Comment by kopurando** [comment]
README updated, I hope it's more helpful now.
https://github.com/kopurando/better-faster-elastic-beanstalk
