### ISSUE TITLE
Explanation On Installation 

### ISSUE THREAD

**Issue by AdventuresOfMar** [kopurando/better-faster-elastic-beanstalk#2]
Hi! Thanks so much for this post, Excuse my naivety, I'm new to AWS. I'm having trouble installing this script. I've added example_env.confg to .ebextensions but not sure where to go from here

**Comment by kopurando** [comment]
Here's good start:
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html

Once you push your project (with env.config included) to your Elastic Beanstalk instance, observe logs and see whether everything works as expected. 

This project requries some advanced knowledge of EB architecture, so it is better to start with simplier env.configs to understand mechanism and then use this repo for examples and inspiration.
